In [1]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house-prices.csv', usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [12]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [13]:
x = base.drop('price', axis = 1)
y = base.price

In [14]:
x.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [15]:
type(x)

pandas.core.frame.DataFrame

In [16]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [17]:
type(y)

pandas.core.series.Series

In [22]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [23]:
import tensorflow as tf

In [25]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [27]:
print(colunas[1])

NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [28]:
from sklearn.model_selection import train_test_split
x_treinamento, x_test, y_treinamento, y_test = train_test_split(x, y , test_size = 0.3)

In [29]:
x_treinamento.shape

(15129, 16)

In [30]:
y_treinamento.shape

(15129,)

In [31]:
x_test.shape

(6484, 16)

In [37]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = x_treinamento, y = y_treinamento, 
                                                         batch_size = 32, num_epochs = None, shuffle = True)

In [38]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = x_test, y = y_test, 
                                                         batch_size = 32, num_epochs = 10000, shuffle = False)

In [41]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpzqsvl1rv', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a31888860>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [42]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpzqsvl1rv/model.ckpt.
INFO:tensorflow:loss = 0.16868182, step = 1
INFO:tensorflow:global_step/sec: 227.617
INFO:tensorflow:loss = 0.025807114, step = 101 (0.442 sec)
INFO:tensorflow:global_step/sec: 353.722
INFO:tensorflow:loss = 0.011621968, step = 201 (0.283 sec)
INFO:tensorflow:global_step/sec

INFO:tensorflow:global_step/sec: 324.008
INFO:tensorflow:loss = 0.015448752, step = 6201 (0.309 sec)
INFO:tensorflow:global_step/sec: 357.403
INFO:tensorflow:loss = 0.022222692, step = 6301 (0.278 sec)
INFO:tensorflow:global_step/sec: 361.779
INFO:tensorflow:loss = 0.0134264, step = 6401 (0.278 sec)
INFO:tensorflow:global_step/sec: 376.125
INFO:tensorflow:loss = 0.02400504, step = 6501 (0.267 sec)
INFO:tensorflow:global_step/sec: 355.568
INFO:tensorflow:loss = 0.012960545, step = 6601 (0.281 sec)
INFO:tensorflow:global_step/sec: 366.045
INFO:tensorflow:loss = 0.0067026904, step = 6701 (0.272 sec)
INFO:tensorflow:global_step/sec: 324.303
INFO:tensorflow:loss = 0.027515374, step = 6801 (0.308 sec)
INFO:tensorflow:global_step/sec: 339.26
INFO:tensorflow:loss = 0.020865135, step = 6901 (0.294 sec)
INFO:tensorflow:global_step/sec: 325.608
INFO:tensorflow:loss = 0.039111704, step = 7001 (0.307 sec)
INFO:tensorflow:global_step/sec: 367.713
INFO:tensorflow:loss = 0.011138719, step = 7101 (0.27

In [43]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-07-23T00:49:08Z
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpzqsvl1rv/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-07-23-00:49:33
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00068062585,

In [44]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-07-23T00:50:38Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpzqsvl1rv/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-07-23-00:51:04
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007471819, global_step = 10000, label/mean = 0.060768913, loss = 0.02390982, prediction/mean = 0.0

In [45]:
metricas_treinamento

{'average_loss': 0.00068062585,
 'label/mean': 0.061084375,
 'loss': 0.021780027,
 'prediction/mean': 0.06094557,
 'global_step': 10000}

In [46]:
metricas_teste

{'average_loss': 0.0007471819,
 'label/mean': 0.060768913,
 'loss': 0.02390982,
 'prediction/mean': 0.06084383,
 'global_step': 10000}

In [47]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = x_test, shuffle = False)

In [48]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [49]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpzqsvl1rv/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.04993875], dtype=float32)},
 {'predictions': array([0.06930856], dtype=float32)},
 {'predictions': array([0.04111174], dtype=float32)},
 {'predictions': array([0.06080735], dtype=float32)},
 {'predictions': array([0.01434764], dtype=float32)},
 {'predictions': array([0.06437618], dtype=float32)},
 {'predictions': array([0.09157171], dtype=float32)},
 {'predictions': array([0.07566936], dtype=float32)},
 {'predictions': array([0.0686309], dtype=float32)},
 {'predictions': array([0.08382482], dtype=float32)},
 {'predictions': array([0.06019682], dtype=float32)},
 {'predictions': array([0.04633837], dtype=float32)},
 {'predictions': array([0.0519098], dtype=float32)},
 {'predictions': array([0.10073217], dtype=float32)},
 {'predictions': array([0.01070566], dtype=float32)},
 {'predictions': array([0.06146591], dtype=float32)},
 {'predictions': array([0.10367375], dtype=float32)},
 {'predictions': array([0.08937182], dtype=float32)},
 {'predictions': array([0.0402

In [50]:
valores_previsoes = []
for p in regressor.predict(input_fn = funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpzqsvl1rv/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [51]:
valores_previsoes

[array([0.04993875], dtype=float32),
 array([0.06930856], dtype=float32),
 array([0.04111174], dtype=float32),
 array([0.06080735], dtype=float32),
 array([0.01434764], dtype=float32),
 array([0.06437618], dtype=float32),
 array([0.09157171], dtype=float32),
 array([0.07566936], dtype=float32),
 array([0.0686309], dtype=float32),
 array([0.08382482], dtype=float32),
 array([0.06019682], dtype=float32),
 array([0.04633837], dtype=float32),
 array([0.0519098], dtype=float32),
 array([0.10073217], dtype=float32),
 array([0.01070566], dtype=float32),
 array([0.06146591], dtype=float32),
 array([0.10367375], dtype=float32),
 array([0.08937182], dtype=float32),
 array([0.04025909], dtype=float32),
 array([0.02230557], dtype=float32),
 array([0.01128867], dtype=float32),
 array([0.12641957], dtype=float32),
 array([0.07137831], dtype=float32),
 array([0.0525623], dtype=float32),
 array([0.10710717], dtype=float32),
 array([0.03730099], dtype=float32),
 array([0.02415119], dtype=float32),
 arr

In [52]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [53]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[455782.94],
       [603477.75],
       [388477.06],
       ...,
       [ 77185.23],
       [395679.97],
       [674582.75]], dtype=float32)

In [54]:
y_test

18780    0.044590
18390    0.062426
21285    0.032000
16180    0.050492
19028    0.028852
14267    0.072131
9067     0.077377
11525    0.046551
302      0.065705
2262     0.049836
4813     0.078689
20790    0.046032
18704    0.080984
3137     0.088852
10959    0.008249
163      0.048000
18195    0.069508
3886     0.085902
9738     0.058098
1885     0.034754
18745    0.016387
12137    0.097049
1482     0.056361
16803    0.029508
2233     0.104918
11889    0.042885
15671    0.035410
19937    0.039344
15173    0.095738
7124     0.039803
           ...   
8419     0.022689
12669    0.034098
9282     0.077377
13977    0.065574
9029     0.036059
2344     0.097049
3611     0.045115
9237     0.081967
9274     0.210492
9354     0.092459
17568    0.042295
19875    0.046557
10304    0.068984
17438    0.032787
21390    0.029508
9636     0.065508
3239     0.020328
10437    0.036066
10203    0.022295
11623    0.070557
13598    0.111475
9027     0.037377
11239    0.039344
9144     0.061639
8292     0

In [55]:
y_test.shape

(6484,)

In [56]:
y_test2 = y_test.values.reshape(-1,1)
y_test2.shape

(6484, 1)

In [57]:
y_test2 = scaler_y.inverse_transform(y_test2)

In [58]:
y_test2

array([[415000.],
       [551000.],
       [319000.],
       ...,
       [ 84000.],
       [439950.],
       [495000.]])

In [59]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test2, valores_previsoes)

In [60]:
mae

125742.8259053498