In [1]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.shape

(21613, 21)

In [3]:
x = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [4]:
x

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [5]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [6]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x = scaler_x.fit_transform(x)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
x

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [8]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [9]:
import tensorflow as tf

In [10]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [11]:
colunas

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [12]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpt6i_3tps', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a2a7144a8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [13]:
from sklearn.model_selection import train_test_split
x_treinamento, x_test, y_treinamento, y_test = train_test_split(x, y, test_size = 0.3)

In [14]:
x_treinamento.shape

(15129, 1)

In [15]:
y_treinamento.shape

(15129, 1)

In [16]:
x_test.shape

(6484, 1)

In [17]:
y_test.shape

(6484, 1)

In [19]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': x_treinamento}, y_treinamento , batch_size = 32, num_epochs = None, shuffle = True)

In [21]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': x_test}, y_test, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [22]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpt6i_3tps/model.ckpt.
INFO:tensorflow:loss = 19.993568, step = 1
INFO:tensorflow:global_step/sec: 489.251
INFO:tensorflow:loss = 23.35199, step = 101 (0.206 sec)
INFO:tensorflow:global_step/sec: 536.516
INFO:tensorflow:loss = 7.160907, step = 201 (0.185 sec)
INFO:tensorflow:global_step/sec: 590.0

INFO:tensorflow:loss = 13.138453, step = 6301 (0.104 sec)
INFO:tensorflow:global_step/sec: 832.902
INFO:tensorflow:loss = 15.352114, step = 6401 (0.120 sec)
INFO:tensorflow:global_step/sec: 984.022
INFO:tensorflow:loss = 8.402961, step = 6501 (0.101 sec)
INFO:tensorflow:global_step/sec: 982.231
INFO:tensorflow:loss = 9.876194, step = 6601 (0.102 sec)
INFO:tensorflow:global_step/sec: 1020.02
INFO:tensorflow:loss = 20.70549, step = 6701 (0.098 sec)
INFO:tensorflow:global_step/sec: 1028.71
INFO:tensorflow:loss = 153.62971, step = 6801 (0.098 sec)
INFO:tensorflow:global_step/sec: 986.243
INFO:tensorflow:loss = 36.732124, step = 6901 (0.101 sec)
INFO:tensorflow:global_step/sec: 1031.76
INFO:tensorflow:loss = 11.267868, step = 7001 (0.096 sec)
INFO:tensorflow:global_step/sec: 998.572
INFO:tensorflow:loss = 22.064941, step = 7101 (0.101 sec)
INFO:tensorflow:global_step/sec: 1025.29
INFO:tensorflow:loss = 11.695526, step = 7201 (0.097 sec)
INFO:tensorflow:global_step/sec: 1079.84
INFO:tensorfl

In [23]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-05T00:44:00Z
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpt6i_3tps/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-06-05-00:44:09
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5165764, glo

In [24]:
metricas_test = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-05T00:45:18Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpt6i_3tps/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-06-05-00:45:27
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.48541704, global_step = 10000, label/mean = -0.00040803742, loss = 15.533345, prediction/mean = -0.

In [27]:
metricas_treinamento

{'average_loss': 0.5165764,
 'label/mean': 0.000306841,
 'loss': 16.530445,
 'prediction/mean': -0.008355469,
 'global_step': 10000}

In [28]:
metricas_test

{'average_loss': 0.48541704,
 'label/mean': -0.00040803742,
 'loss': 15.533345,
 'prediction/mean': -0.016819188,
 'global_step': 10000}

In [29]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [30]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [32]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [33]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [34]:
previsoes

<generator object EstimatorV2.predict at 0x1a2e7ba570>

In [35]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpt6i_3tps/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.97891164], dtype=float32)},
 {'predictions': array([-0.9032825], dtype=float32)},
 {'predictions': array([-0.8276533], dtype=float32)}]

In [37]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/kv/py6frwmj5kx29vvvw4m51td40000gn/T/tmpt6i_3tps/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[180711.36]
[208476.23]
[236241.14]
